ensure defining W32LockFile and W32UnlockFile before they are used
fixes compilation errors on some windows systems :

Output from 'C:\strawberry180\c\bin\dmake.exe':

cp lib/XML/TinyXML/Selector/XPath.pm blib\lib\XML\TinyXML\Selector\XPath.pm
cp lib/XML/TinyXML/Selector/XPath/Axes.pm blib\lib\XML\TinyXML\Selector\XPath\Axes.pm
cp lib/XML/TinyXML/Selector/XPath/Functions.pm blib\lib\XML\TinyXML\Selector\XPath\Functions.pm
cp lib/XML/TinyXML/Selector/XPath/Context.pm blib\lib\XML\TinyXML\Selector\XPath\Context.pm
cp lib/XML/TinyXML/Selector.pm blib\lib\XML\TinyXML\Selector.pm
cp lib/XML/TinyXML.pm blib\lib\XML\TinyXML.pm
AutoSplitting blib\lib\XML\TinyXML.pm (blib\lib\auto\XML\TinyXML)
cp lib/XML/TinyXML/Node.pm blib\lib\XML\TinyXML\Node.pm
cp lib/XML/TinyXML/NodeAttribute.pm blib\lib\XML\TinyXML\NodeAttribute.pm
C:\strawberry180\perl\bin\perl.exe C:\strawberry180\perl\lib\ExtUtils\xsubpp  -typemap C:\strawberry180\perl\lib\ExtUtils\typemap -typemap typemap  TinyXML.xs > TinyXML.xsc && C:\strawberry180\perl\bin\perl.exe -MExtUtils::Command -e mv -- TinyXML.xsc TinyXML.c
gcc -c  -I.     -s -O2 -DWIN32 -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -s -O2        -DVERSION=\"0.30\"    -DXS_VERSION=\"0.30\"  "-IC:\strawberry180\perl\lib\CORE"   TinyXML.c
In file included from ./txml.h:23:0,
                 from TinyXML.xs:5:
                 ./bsd_queue.h:146:0: warning: "SLIST_ENTRY" redefined [enabled by default]
                 c:\strawberry180\c\bin\../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/include/winnt.h:5564:0: note: this is the location of the previous definition
                 gcc -c  -I.    -s -O2 -DWIN32 -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fno-strict-aliasing -mms-bitfields -s -O2        -DVERSION=\"0.30\"    -DXS_VERSION=\"0.30\"  "-IC:\strawberry180\perl\lib\CORE"   txml.c
                 txml.c:69:5: warning: '_errno' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
                 txml.c:2026:1: error: static declaration of 'W32LockFile' follows non-static declaration
                 txml.c:1160:15: note: previous implicit declaration of 'W32LockFile' was here
                 txml.c:2058:1: error: static declaration of 'W32UnlockFile' follows non-static declaration
                 txml.c:1182:12: note: previous implicit declaration of 'W32UnlockFile' was here
                 dmake.exe:  Error code 129, while making 'txml.o'